// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © jusstakinn

//@version=5
indicator(title="Moving Average/ofs with Volatility Rate", shorttitle="MA / EMA ofs t/b", overlay=true, timeframe="D", timeframe_gaps=true)


//isWeekly = timeframe.period == "W"
//isDaily = timeframe.period == "D"
lenMAs = input.int(150, minval=1, title="LengthMAs(Day)")


//if timeframe.period == "W"
//   lenMAs := input.int(9, minval=1, title="LengthMAs(Week)")
src = input(close, title="Source")



length = 500 // Number of days to consider
// Calculate the standard deviation
stdDev = ta.stdev(close, length) 
// Calculate the average price over the last 365 days
avgPrice = ta.sma(close, length)
// Calculate the standard deviation divided by the average price
stdDevRatio = (stdDev / avgPrice)
//avgStdDevRatio = ta.sma(stdDevRatio, length)
volatilityRate = stdDevRatio * 100
//volatilityRate = 35


percentageShift = math.pow((1+(0.115 * volatilityRate)), (0.1))

band1 = src/(math.pow((1+(0.115 * volatilityRate)), (0.5)))
band2 = band1 * percentageShift
band3 = band1 * math.pow(percentageShift, 2)
band4 = band1 * math.pow(percentageShift, 3)
band5 = band1 * math.pow(percentageShift, 4)
band6 = band1 * math.pow(percentageShift, 5)
band7 = band1 * math.pow(percentageShift, 6)
band8 = band1 * math.pow(percentageShift, 7)
band9 = band1 * math.pow(percentageShift, 8)
band10 = band1 * math.pow(percentageShift, 9)
band11 = band1 * math.pow(percentageShift, 10)

outMa1 = ta.ema(band1, lenMAs)
outMa2 = ta.ema(band2, lenMAs)
outMa3 = ta.ema(band3, lenMAs)
outMa4 = ta.ema(band4, lenMAs)
outMa5 = ta.ema(band5, lenMAs)
outMa6 = ta.ema(band6, lenMAs)
outMa7 = ta.ema(band7, lenMAs)
outMa8 = ta.ema(band8, lenMAs)
outMa9 = ta.ema(band9, lenMAs)
outMa10 = ta.ema(band10, lenMAs)
outMa11 = ta.ema(band11, lenMAs)



plot(outMa1, color=color.rgb(243, 152, 33), title="MA1")
plot(outMa2, color=color.rgb(170, 243, 33), title="MA2")
plot(outMa3, color=color.rgb(33, 243, 86), title="MA3")
plot(outMa4, color=color.rgb(33, 243, 173), title="MA4")
plot(outMa5, color=color.rgb(33, 184, 243), title="MA5")
plot(outMa6, color=color.rgb(33, 72, 243), title="MA6")
plot(outMa7, color=color.rgb(33, 65, 243), title="MA7")
plot(outMa8, color=color.rgb(47, 33, 243), title="MA8")
plot(outMa9, color=color.rgb(149, 33, 243), title="MA9")
plot(outMa10, color=color.rgb(236, 33, 243), title="MA10")
plot(outMa11, color=color.rgb(243, 33, 61), title="MA11")